Update obsolete cop names
As of Rubocop 0.77 these are obsolete:

> Error: The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`.
> (obsolete configuration found in .rubocop.yml, please update it)
> The `Layout/IndentFirstArrayElement` cop has been renamed to `Layout/FirstArrayElementIndentation`.
> (obsolete configuration found in .rubocop.yml, please update it)
> The `Layout/IndentFirstHashElement` cop has been renamed to `Layout/FirstHashElementIndentation`.
> (obsolete configuration found in .rubocop.yml, please update it)